[package]
name = "hello-world"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[dependencies]
wit-bindgen = { workspace = true }
stdlib = { workspace = true }

[lib]
crate-type = ["cdylib"]
